services:

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - ./db/data/:/var/lib/mysql
    ports:
      - ${PORT_DB:-3306}:3306
    environment:
      MARIADB_ROOT_PASSWORD: 1
    container_name: m2_db
    networks:
      php-db:
        ipv4_address: 10.10.0.100

  httpd:
    build: ./httpd
    volumes:
      - ./httpd/conf:/usr/local/apache2/conf/docker:ro
      - ./public_html:/var/www/html/:ro
    ports:
      - ${PORT:-80}:80
      - 443:443
    container_name: m2_httpd
    networks:
      php-httpd:

  php:
    build:
      context: ./php74
      args:
        USER: #leave it empty to use your current user
        UID: ${UID:-501}
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./public_html:/var/www/html
    container_name: m2_php74
    networks:
      php-db:
      php-httpd:
      php-es:

  php56:
    build:
      context: ./php56
      args:
        USER: #leave it empty to use your current user
        UID: ${UID:-501}
    volumes:
      - ./public_html:/var/www/html
    container_name: m2_php56
    networks:
      php-db:
      php-httpd:

  php73:
    build:
      context: ./php73
      args:
        USER: #leave it empty to use your current user
        UID: ${UID:-501}
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE:-debug}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./public_html:/var/www/html
    container_name: m2_php73
    networks:
      php-db:
      php-httpd:
      php-es:

  elasticsearch:
    image: elasticsearch:7.14.1
    environment:
      - discovery.type=single-node
    container_name: m2_elastic
    networks:
      php-es:

networks:
  php-db:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
  php-httpd:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.0.0/24
  php-es:
    driver: bridge
    ipam:
      config:
        - subnet: 10.30.0.0/24
