services:

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - ./db/data/:/var/lib/mysql
    ports:
      - ${PORT_DB:-3306}:3306
    environment:
      MARIADB_ROOT_PASSWORD: Z4yk8pV4
    container_name: db
    networks:
      php-db:
        ipv4_address: 10.10.0.100

  httpd:
    build: ./httpd
    volumes:
      - ./httpd/conf:/usr/local/apache2/conf/docker:ro
      - ./public_html:/var/www/html/:ro
    ports:
      - ${PORT:-80}:80
      - 443:443
    container_name: httpd
    networks:
      php-httpd:

  php:
    build:
      context: ./php74
      args:
        USER: #leave it empty to use your current user
        UID: ${UID:-1000}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./public_html:/var/www/html
      - ./php74/config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    container_name: php74
    user: '1000:1000'
    networks:
      php-db:
      php-httpd:
  
  elasticsearch:
    image: elasticsearch:7.9.0
    container_name: elastic
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data2:/dockerData/elasticsearchM2/data
    ports:
      - 9200:9200
    networks:
      php-es:

  ddclient:
    image: lscr.io/linuxserver/ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./config:/config
    restart: unless-stopped

  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/site:/srv
      - ./caddy/caddy_data:/data
      - ./caddy/caddy_config:/config

networks:
  php-db:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
  php-httpd:
    driver: bridge
    ipam:
      config:
        - subnet: 10.20.0.0/24
  php-es:
    driver: bridge
    ipam:
      config:
        - subnet: 10.30.0.0/24

volumes:
  data2:
  caddy_data:
    external: true
  caddy_config:
